export const FETCH_HISTORY_START = 'FETCH_HISTORY_START'
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS'
export const FETCH_HISTORY_DETAIL_START = 'FETCH_HISTORY_DETAIL_START'
export const FETCH_HISTORY_DETAIL_SUCCESS = 'FETCH_HISTORY_DETAIL_SUCCESS'
